---
- name: Running show commands using ios_command module
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run multiple commands on Cisco routers
      ios_command:
        commands:
          - show version
          - show clock

      register: print_output

    - debug: var=print_output.stdout_lines