---

- name: configuring Arista vEOS devices
  gather_facts: no
  hosts: arista
  connection: network_cli

  vars:
    ansible_user: bigg
    ansible_ssh_pass: bigg
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: bigg
    ansible_network_os: eos

  tasks:
    - name: Basic Arista Configuration
      eos_config:
        save_when: modified
        lines:
          - username ansible role network-admin secret bigg
          - ip name-server 8.8.8.8
#          - ip domain name bigogigo.com
      register: output

    - name: Printing at the console
      debug: var=output